import 'dart:io';
import 'dart:convert';
import 'package:http/http.dart' as http;

void main() async {
  const supabaseUrl = 'https://hrlciruepdstrvtsuoyr.supabase.co';
  const apiKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhybGNpcnVlcGRzdHJ2dHN1b3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMxMDA4MjgsImV4cCI6MjA5ODY3NjgyOH0.-FqYflyY-0333oNlC5clOpcOm_E60R6e9WULp_xZHEo';

  // Tamil name mapping
  final tamilMap = <String, String>{
    'surf excel': 'சர்ப் எக்ஸல்',
    'wheel': 'வீல்',
    'rin': 'ரின்',
    'nirma': 'நிர்மா',
    'vim': 'விம்',
    'pril': 'ப்ரில்',
    'lux': 'லக்ஸ்',
    'dove': 'டவ்',
    'rexona': 'ரெக்சோனா',
    'hamam': 'ஹமம்',
    'cinthol': 'சிந்தால்',
    'dettol': 'டெட்டால்',
    'colgate': 'கல்கேட்',
    'pepsodent': 'பெப்சோடென்ட்',
    'closeup': 'குளோஸ் அப்',
    'himalaya': 'ஹிமாலயா',
    'amul': 'அமூல்',
    'tide': 'டைட்',
    'ariel': 'அரியல்',
    'surf': 'சர்ப்',
    'excel': 'எக்ஸல்',
    'maggi': 'மேகி',
    'parle': 'பார்லே',
    'dairy milk': 'டைரி மில்க்',
    'kitkat': 'கிட்காட்',
    '5 star': '5 ஸ்டார்',
    'gems': 'ஜெம்ஸ்',
    'horlicks': 'ஹார்லிக்ஸ்',
    'boost': 'பூஸ்ட்',
    'good day': 'குட் டே',
    'sunfeast': 'சன்ஃபெஸ்ட்',
    'bingo': 'பிங்கோ',
    'lays': 'லேஸ்',
    'marie': 'மேரி',
    'tea': 'தேநீர்',
    'coffee': 'காபி',
    'milk': 'பால்',
    'sugar': 'சர்க்கரை',
    'oil': 'எண்ணெய்',
    'rice': 'அரிசி',
    'dal': 'பருப்பு',
    'soap': 'சோப்பு',
    'shampoo': 'ஷாம்பு',
    'powder': 'பொடி',
    'biscuit': 'பிஸ்கட்',
    'chocolate': 'சாக்லேட்',
    'pen': 'பேனா',
    'notebook': 'நோட்டுப் புத்தகம்',
    'bottle': 'புட்டில்',
    'toothpaste': 'பற்பசை',
    'cream': 'கிரீம்',
    'matchbox': 'தீக்குச்சி பெட்டி',
    'candle': 'மெழுகுவர்த்தி',
    'battery': 'பேட்டரி',
    'glue': 'ஒட்டும் பசை',
    'fan': 'மின்விசிறி',
    'light': 'லைட்',
    'switch': 'சுவிட்ச்',
    'wire': 'வயர்',
    'tape': 'டேப்',
    'chips': 'சிப்ஸ்',
    'noodles': 'நூடுல்ஸ்',
    'paste': 'பேஸ்ட்',
    'juice': 'ஜூஸ்',
    'water': 'தண்ணீர்',
    'pack': 'பேக்',
    'box': 'பெட்டி',
    'bag': 'பை',
    'salt': 'உப்பு',
    'perungayam': 'பெருங்காயம்',
    'brinjal': 'கத்திரிக்காய்',
    'tomato': 'தக்காளி',
    'onion': 'வெங்காயம்',
    'chilli': 'மிளகாய்',
    'pepper': 'மிளகு',
    'cumin': 'சீரகம்',
    'coriander': 'மல்லி',
    'mustard': 'கடுகு',
    'fenugreek': 'வெந்தயம்',
    'turmeric': 'மஞ்சள்',
    'ginger': 'இஞ்சி',
    'garlic': 'பூண்டு',
    'coconut': 'தேங்காய்',
    'lemon': 'எலுமிச்சை',
    'banana': 'வாழைப்பழம்',
    'apple': 'ஆப்பிள்',
    'orange': 'ஆரஞ்சு',
    'grapes': 'திராட்சை',
    'mango': 'மாம்பழம்',
    'potato': 'உருளைக்கிழங்கு',
    'curd': 'தயிர்',
    'butter': 'வெண்ணெய்',
    'ghee': 'நெய்',
    'paneer': 'பன்னீர்',
    'cheese': 'சீஸ்',
    'egg': 'முட்டை',
    'chicken': 'கோழி',
    'fish': 'மீன்',
    'prawn': 'இறால்',
    'mutton': 'ஆட்டிறைச்சி',
    'beef': 'மாட்டிறைச்சி',
    'pork': 'பன்றிறைச்சி',
    'sausage': 'சாசேஜ்',
    'bacon': 'பேகன்',
    'ham': 'ஹாம்',
    'bread': 'ரொட்டி',
    'bun': 'பன்',
    'cake': 'கேக்',
    'pastry': 'பேஸ்ட்ரி',
    'cookie': 'குக்கீ',
    'waffle': 'வாஃபிள்',
    'pancake': 'பான்கேக்',
    'cereal': 'சீரியல்',
    'oats': 'ஓட்ஸ்',
    'cornflakes': 'கார்ன்பிளேக்ஸ்',
    'muesli': 'மியூஸ்லி',
    'granola': 'கிரனோலா',
    'honey': 'தேன்',
    'jam': 'ஜாம்',
    'jelly': 'ஜெல்லி',
    'syrup': 'சிரப்',
    'ketchup': 'கெச்சப்',
    'sauce': 'சாஸ்',
    'vinegar': 'வினிகர்',
    'pickle': 'ஊறுகாய்',
    'chutney': 'சட்னி',
    'papad': 'அப்பளம்',
    'fryums': 'ஃப்ரையம்ஸ்',
    'mixture': 'மிக்சர்',
    'namkeen': 'நம்கீன்',
    'sev': 'சேவ்',
    'boondi': 'பூந்தி',
    'murukku': 'முறுக்கு',
    'omapodi': 'ஓமப்பொடி',
    'ribbon': 'ரிப்பன்',
    'pakoda': 'பகோடா',
    'bajji': 'பஜ்ஜி',
    'vada': 'வடை',
    'bonda': 'போண்டா',
    'bhel': 'பேல்',
    'pani puri': 'பானி பூரி',
    'dosa': 'தோசை',
    'idli': 'இட்லி',
    'vadai': 'வடை',
    'pongal': 'பொங்கல்',
    'upma': 'உப்புமா',
    'kesari': 'கேசரி',
    'halwa': 'அல்வா',
    'laddu': 'லட்டு',
    'barfi': 'பர்ஃபி',
    'jalebi': 'ஜிலேபி',
    'gulab jamun': 'குலாப் ஜாமுன்',
    'rasmalai': 'ரஸ்மலாய்',
    'kulfi': 'குல்பி',
    'lassi': 'லஸ்ஸி',
    'buttermilk': 'மோர்',
    'curd': 'தயிர்',
    'yogurt': 'தயிர்',
    'lassi': 'லஸ்ஸி',
    'thandai': 'தாண்டாய்',
    'badam milk': 'பாதாம் பால்',
    'saffron': 'குங்குமப்பூ',
    'pista': 'பிஸ்தா',
    'kaju': 'காஜு',
    'badam': 'பாதாம்',
    'akrot': 'அக்ரூட்',
    'dry fruit': 'உலர் பழம்',
    'paan': 'பான்',
    'supari': 'சுபாரி',
    'gutkha': 'குட்கா',
    'beedi': 'பீடி',
    'cigarette': 'சிகரெட்',
    'tobacco': 'புகையிலை',
    'pan masala': 'பான் மசாலா',
    'incense': 'ஊதுவத்தி',
    'agarbatti': 'அகர்பத்தி',
    'sambrani': 'சாம்பிராணி',
    'camphor': 'கற்பூரம்',
    'kumkumam': 'குங்குமம்',
    'turmeric powder': 'மஞ்சள் பொடி',
    'chilli powder': 'மிளகாய் தூள்',
    'coriander powder': 'மல்லி தூள்',
    'garam masala': 'கரம் மசாலா',
    'sambar powder': 'சாம்பார் பொடி',
    'rasam powder': 'ரசம் பொடி',
    'curry powder': 'கறி பொடி',
    'red chilli': 'சிவப்பு மிளகாய்',
    'toothbrush': 'பல் துலக்கி',
    'razor': 'ரேசர்',
    'blade': 'பிளேட்',
    'scissors': 'கத்திரிக்கோல்',
    'knife': 'கத்தி',
    'plate': 'தட்டு',
    'cup': 'கோப்பை',
    'glass': 'கிளாஸ்',
    'bowl': 'கிண்ண்',
    'spoon': 'கரண்டி',
    'fork': 'முள்கரண்டி',
    'pencil': 'பென்சில்',
    'eraser': 'அழிப்பான்',
    'sharpener': 'தீட்டி',
    'stapler': 'ஸ்டேப்ளர்',
    'rubber band': 'ரப்பர் பேண்ட்',
    'clip': 'கிளிப்',
    'pin': 'பின்',
    'ruler': 'அளவுகோல்',
    'compass': 'கம்பாஸ்',
    'marker': 'மார்க்கர்',
    'highlighter': 'ஹைலைட்டர்',
    'marker pen': 'மார்க்கர் பேனா',
    'sketch pen': 'ஸ்கெட்ச் பேனா',
    'crayon': 'கிரேயான்',
    'color': 'நிறம்',
    'paint': 'நிறம்',
    'brush': 'பிரஷ்',
    'canvas': 'கேன்வாஸ்',
    'paper': 'தாள்',
    'tissue': 'டிஷ்யூ',
    'napkin': 'நாப்கின்',
    'diaper': 'டயாபர்',
    'wipes': 'வைப்ஸ்',
    'sanitizer': 'சானிடைசர்',
    'mask': 'மாஸ்க்',
    'glove': 'கையுறை',
    'shoe': 'ஷூ',
    'slipper': 'செருப்பு',
    'chappal': 'சப்பல்',
    'sandal': 'சாண்டல்',
    'body wash': 'உடல் கழுவு',
    'hand wash': 'கை கழுவு',
    'face wash': 'முகம் கழுவு',
    'conditioner': 'கண்டிஷனர்',
    'hair oil': 'தலைமுடி எண்ணெய்',
    'hair cream': 'தலைமுடி கிரீம்',
    'hair dye': 'தலைமுடி சாயம்',
    'hair color': 'தலைமுடி நிறம்',
    'hair gel': 'தலைமுடி ஜெல்',
    'hair spray': 'தலைமுடி ஸ்ப்ரே',
    'mouthwash': 'வாய் கழுவும் திரவம்',
    'dental floss': 'பல் நூல்',
    'shaving cream': 'கருவரல் கிரீம்',
    'after shave': 'ஆஃப்டர் ஷேவ்',
    'deodorant': 'டியோடரண்ட்',
    'perfume': 'பெர்ஃப்யூம்',
    'cologne': 'கோலோன்',
    'talcum powder': 'டால்கம் பொடி',
    'body powder': 'உடல் பொடி',
    'moisturizer': 'ஈரப்பதமூட்டி',
    'sunscreen': 'சன் ஸ்கிரீன்',
    'lip balm': 'லிப் பாம்',
    'vaseline': 'வாஸலின்',
    'glycerin': 'கிளிசரின்',
    'aloe vera': 'அலோ வேரா',
    'neem': 'வேம்பு',
    'tulsi': 'துளசி',
    'sandal': 'சந்தன்',
    'rose': 'ரோஜா',
    'jasmine': 'மல்லிகை',
    'camphor': 'கற்பூரம்',
    'menthol': 'மெந்தால்',
    'peppermint': 'பெப்பர்மிண்ட்',
    'eucalyptus': 'யூகலிப்டஸ்',
    'clove oil': 'கிராம்பு எண்ணெய்',
    'petroleum jelly': 'பெட்ரோலியம் ஜெல்லி',
    'petrol': 'பெட்ரோல்',
    'diesel': 'டீசல்',
    'coal': 'நிலக்கரி',
    'charcoal': 'மரக்கரி',
    'plastic': 'பிளாஸ்டிக்',
    'rubber': 'ரப்பர்',
    'glass': 'கண்ணாடி',
    'metal': 'உலோகம்',
    'iron': 'இரும்பு',
    'steel': 'ஸ்டீல்',
    'copper': 'செம்பு',
    'brass': 'பித்தளை',
    'aluminium': 'அலுமினியம்',
    'silver': 'வெள்ளி',
    'gold': 'தங்கம்',
    'diamond': 'வைரம்',
    'pearl': 'முத்து',
    'marble': 'பளிங்கு',
    'granite': 'கிரானைட்',
  };

  print('Fetching all products...');
  final response = await http.get(
    Uri.parse('$supabaseUrl/rest/v1/products?select=id,name&order=name&limit=1000'),
    headers: {'apikey': apiKey, 'Authorization': 'Bearer $apiKey'},
  );
  final products = jsonDecode(response.body) as List;
  print('Total products: ${products.length}');

  // Build updates
  final updates = <Map<String, dynamic>>[];
  for (final p in products) {
    final name = (p['name'] as String).toLowerCase();
    String? tamil;

    // Try exact match first, then partial
    for (final entry in tamilMap.entries) {
      if (name.contains(entry.key)) {
        tamil = entry.value;
        break;
      }
    }

    if (tamil != null) {
      updates.add({'id': p['id'], 'tamil_name': tamil});
    }
  }

  print('Products to update: ${updates.length}');

  // Batch update via RPC
  const batchSize = 50;
  for (var i = 0; i < updates.length; i += batchSize) {
    final batch = updates.sublist(i, (i + batchSize).clamp(0, updates.length));
    final body = jsonEncode({'products_json': batch});

    final rpcResponse = await http.post(
      Uri.parse('$supabaseUrl/rest/v1/rpc/update_tamil_names'),
      headers: {
        'apikey': apiKey,
        'Authorization': 'Bearer $apiKey',
        'Content-Type': 'application/json',
      },
      body: body,
    );

    if (rpcResponse.statusCode == 200) {
      print('Updated ${i + batch.length} / ${updates.length}');
    } else {
      print('Error: ${rpcResponse.statusCode} ${rpcResponse.body}');
    }
  }

  print('\nDone! Updated $updates products with Tamil names.');

  // Verify
  final verifyResponse = await http.get(
    Uri.parse('$supabaseUrl/rest/v1/products?select=name,tamil_name&limit=5'),
    headers: {'apikey': apiKey, 'Authorization': 'Bearer $apiKey'},
  );
  final verify = jsonDecode(verifyResponse.body) as List;
  print('\nVerification:');
  for (final p in verify) {
    print('${p['name']} -> ${p['tamil_name']}');
  }
}
